ant:
    resource: "@AntWebBundle/Resources/config/routing.yml"
    prefix:   /

gallery:
    resource: '@AntMediaBundle/Resources/config/routing/gallery.yml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media