web_stock:
    resource: "@WebStockBundle/Resources/config/routing.yml"
    prefix:   /

antweb:
    resource: "@AntWebBundle/Resources/config/routing.yml"
    prefix:   /

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart

page_delivery:
    pattern: /{_locale}/delivery_payment
    defaults: { _controller: "AntWebBundle:Page:show", id: "1" }
    requirements:
        _locale: en|ru
page_about:
    pattern: /{_locale}/about
    defaults: { _controller: "AntWebBundle:Page:show", id: "2" }
    requirements:
        _locale: en|ru
page_return:
    pattern: /{_locale}/return
    defaults: { _controller: "AntWebBundle:Page:show", id: "3" }
    requirements:
        _locale: en|ru
#
#sylius_addressing:
#    resource: @SyliusAddressingBundle/Resources/config/routing.yml

