<?php

namespace Web\StockBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Item_In_StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemInStockRepository extends EntityRepository
{
}
